name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "nomduregistre" # Nom du registy
  IMAGE_NAME: "backend-app" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build de l’image Docker
        run: docker build -t my-image:latest .

      - name: Taguer l’image
        run: docker tag my-image:latest ${{ secrets.EXO_REGISTRY_URL }}/c213-emf/my-repo:latest

      - name: Push de l’image sur la registry
        run: docker push ${{ secrets.EXO_REGISTRY_URL }}/c213-emf/my-repo:latest
