name: Build and save my Docker image to a regitry

on:
  push:
    paths:
      - 'todo-app/src/backend/**'
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com" # Nom du registy
  IMAGE_NAME: "todo-app-tp" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Exoscale Registry
        run: echo "${{ secrets.EXO_REGISTRY_PASSWORD }}" | docker login ${{ env.REG_NAME }} -u ${{ secrets.EXO_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker Image
        working-directory: ./todo-app/src/backend
        run: docker build -t ${{ env.IMAGE_NAME }}:latest

      - name: Tag Docker Image
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image
        run: docker push ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:latest
